enableAllRules = true

[rule.package-comments]
Disabled = true
[rule.unused-parameter]
Disabled = true
[rule.unused-receiver]
Disabled = true
[rule.exported]
Disabled = true
[rule.max-public-structs]
Disabled = true
[rule.use-errors-new]
Disabled = true
[rule.cyclomatic]
Disabled = true
[rule.cognitive-complexity]
Disabled = true
[rule.add-constant]
Disabled = true
[rule.function-length]
Disabled = true
[rule.var-declaration]
Disabled = true

[rule.line-length-limit]
arguments = [120]
