---
name: Branch proposal

on:
  pull_request:
    branches-ignore: [main]
    types:
      - opened
      - reopened
      - ready_for_review
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  distros:
    timeout-minutes: 10
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workspace repo
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}
          repository: orglang/go-workspace
      - uses: ./.github/actions/checkout-repos
      - uses: ./.github/actions/setup-tools
      - run: task distros
