---
name: Task proposal

on:
  push:
    branches: [main]
  pull_request:
    branches-ignore: [main]
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./go-engine

jobs:
  building:
    name: Build binaries
    timeout-minutes: 10
    permissions:
      checks: write
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workspace repo
        uses: actions/checkout@v6
        with:
          repository: orglang/workspace
      - name: Checkout sdk repo
        uses: actions/checkout@v6
        with:
          repository: orglang/go-sdk
          path: go-sdk
      - name: Checkout runtime repo
        uses: actions/checkout@v6
        with:
          repository: orglang/go-engine
          path: go-engine
      - name: Setup go
        uses: actions/setup-go@v6.2.0
        with:
          go-version: '1.25'
      - name: Setup task
        uses: go-task/setup-task@v1
      - name: Build binaries
        run: task binaries
