---
name: Trunk proposal

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - reopened
      - ready_for_review
  merge_group:
    branches: [main]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  stacks:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        stack:
          - ops: commons
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workspace repo
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}
          repository: orglang/go-workspace
      - uses: ./.github/actions/checkout-repos
        with:
          ref: ${{ github.ref }}
      - uses: ./.github/actions/setup-tools
      - run: task stack:${{ matrix.stack.ops }}
